# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!

target 'happybets' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
      # Pods for happybets
    pod 'Firebase/Core'
    pod 'Firebase/Analytics'
    pod 'Firebase/Database'
    pod 'Firebase/Auth'

    target 'happytests' do
        inherit! :search_paths
        pod 'Firebase'
    end
end
